updated main.tf and added a shell script to automate the sam build
BCDevOps/terraform-octk-aws-sea-rocketchat-notifications pull request #2
Opened 2021-08-03 21:18 UTC by prabhukiran9999

2021-08-25 17:56 UTC, prabhukiran9999 commented
Added build.sh script

2021-10-05 16:57 UTC, wrnu requested changes

2021-10-05 16:57 UTC, wrnu commented on rocketchat-notification/main.tf
> -  source_code_hash = filebase64sha256("../../builds/securityhubfindings-to-rocketchat.zip")
We'll want to keep this to trigger updates when the function code changes (with the updated path).

2021-10-13 17:16 UTC, wrnu approved these changes

2021-10-13 17:16 UTC, merged